baseURL = "//puffer.blog/"
title = "河豚博客"
publishdir = "docs"
disableHugoGeneratorInject = true
disableLiveReload =true
hasCJKLanguage = true
disableKinds = ["RSS", "sitemap"]
[minify]
  minifyOutput = true

[params]
	[[params.navlinks]]
	name = "about/"
	url = "/about/"
	
	[[params.navlinks]]
	name = "posts/"
	url = "/posts/"
	
	[[params.navlinks]]
	name = "donate/"
	url = "/donate/"